package com.example.shop.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Customer")
public class Customer implements Serializable  {

	private static final long serialVersionUID = 1L;
	
	private String customerId;
	private String customerName;
	
	@DynamoDBHashKey(attributeName = "CustomerId")
	@DynamoDBAutoGeneratedKey
	public String getCustomerId() {
		return customerId;
	}
	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}
	@DynamoDBRangeKey(attributeName = "CustomerName")
	public String getCustomerName() {
		return customerName;
	}
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	
	
	@Override
	public String toString() {
		return "Customer [CustomerId=" + customerId + ", CustomerName=" + customerName + "]";
	}
	
	

}
